#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
postProcess -func writeCellCentres
runApplication $(getApplication)
python3 test_rect.py 
