version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

updates:
  - package-ecosystem: "pip"
    directory: "/tests"
    schedule:
      interval: "weekly"
