#!/bin/sh
cd "${0%/*}" || exit
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

cp system/controlDict.orig system/controlDict

runApplication blockMesh

runApplication $(getApplication)

foamDictionary -entry "endTime" -set 90 system/controlDict
runApplication -append $(getApplication)
