name: Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      arm64:
        description: Build multi-platform image including arm64
        type: boolean
        required: false
        default: false

env:
  PLATFORMS: |
    linux/amd64
    ${{ (inputs.arm64 || github.event_name == 'push') && 'linux/arm64' || '' }}
  IMAGES: |
    ${{ vars.DOCKERHUB_REPOSITORY || github.repository }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker meta (default)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: latest=false
      - name: Docker meta (run)
        id: meta_run
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGES }}
          tags: |
            type=raw,value=run,enable={{is_default_branch}}
          flavor: latest=false
      - name: Login to DockerHub
        if: vars.DOCKERHUB_REPOSITORY
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (default)
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name == 'push' }}
      - name: Build and push (run)
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ env.PLATFORMS }}
          tags: ${{ steps.meta_run.outputs.tags }}
          labels: ${{ steps.meta_run.outputs.labels }}
          target: run
          push: ${{ github.event_name == 'push' }}
